name: Main workflow
on: [push]
jobs:
  run:
    name: Run
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
    steps:
      - uses: actions/checkout@master

      - name: Set Node.js 14.x
        uses: actions/setup-node@master
        with:
          node-version: 14.x

      - name: npm install
        run: npm install

      - name: npm test
        run: npm test
